### ISSUE TITLE
Debian GNU/Linux 12 shim-15.6-1 x64, ia32 and aarch64

### ISSUE THREAD

**Issue by steve-mcintyre** [rhboot/shim-review#267]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/steve-mcintyre/shim-review/tree/debian-12-shim-amd64-arm64-i386-20220806`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
```
74afeac0e6d640c9f5de6fbbce79eae34a7719a3654fcffec8e2e03028c482ae  shimx64.efi
ebbb83c7c7b22e353ef4580b4e7a690c895226122d9c0dce0ac1eb1b9b87ecda  shimaa64.efi
69dc1b4a118a74a4d4162a7dd0532b488bb7837cc9d948c600d7ec2139ee9d81  shimia32.efi
```

**Comment by ecos-platypus** [comment]
Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.

Review was conducted in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines)

1. The vendor is well-known, last accepted shim was #185, security contacts and their keys did not change
- For future reviews: It would be easier to compare old and new pgp keys if they all were in the armored ascii format, currently the security-team PGP key is a binary key but imports as the same key as the one in #185
2. Build reproduces for `shimx64.efi`, the other archs are not built via the Dockerfile
3. shim is built from https://salsa.debian.org/efi-team/shim.git rather than the release tar.gz. I diffed the shim 15.6 tag with the current master of the git repository and there were no changes in the code
4. All questions in the review template and README.md are answered
5. The embedded CA certificate is a self-signed certificate with `CN = Debian Secure Boot CA`
6. Private keys are stored in a HSM
7. The embedded self-signed CA certificate has a validity of 30 years (2016 - 2046) and was accepted before
8. SBAT data in `shimia32.efi` and `shimx64.efi` matches the one in README.md, I was not able to check `shimaa64.efi` via `objdump -s -j .sbat shimaa64.efi`
8.1. The vendor extension `debian` is sensible
8.2. The shim and GRUB builds are not derived from another distro and sbat therefore does not need to include intermediary entries
9. GRUB is used as bootloader
10.1. GRUB has all required CVE patches
10.2. Debian has a lot of custom GRUB patches but that was not an issue in past reviews
11. Kernel 5.18.5 is used and includes the required lockdown patches
12. Revocation is achieved with multiple measures:
- old signing certificates have been revoked and replaced with component-specific signing certificates
- embedded dbx that blocks all vulnerable GRUBs issues before SBAT
- SBAT is used for further revocation
13. Secure boot enforcement is described appropriately (GRUB with secure boot patches, Linux kernel with lockdown patches, fwupd will not execute other binaries)

Things to consider:
- I am not sure about the sbat data. Shouldn't `grub.shim` and `grub.debian` follow the `shim` and `grub` "generation" and move from generation 1 to 2?

**Comment by julian-klode** [comment]
> I am not sure about the sbat data. Shouldn't grub.shim and grub.debian follow the shim and grub "generation" and move from generation 1 to 2?

No. They can't go backwards (which I just realized) but they don't have to go upward, they are totally unrelated. You'd only ever bump them if you have custom security bugs fixed outside of a regular grub update (or well same for any other component).

**Comment by steve-mcintyre** [comment]
> Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.
> 
> Review was conducted in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines)
> 
>     1. The vendor is well-known, last accepted shim was [Debian GNU/Linux 11 shim-15.4-6 x64 and ia32 (20210623) #185](https://github.com/rhboot/shim-review/issues/185), security contacts and their keys did not change
> 
> 
>     * For future reviews: It would be easier to compare old and new pgp keys if they all were in the armored ascii format, currently the security-team PGP key is a binary key but imports as the same key as the one in [Debian GNU/Linux 11 shim-15.4-6 x64 and ia32 (20210623) #185](https://github.com/rhboot/shim-review/issues/185)

ACK, good suggestion!

>     2. Build reproduces for `shimx64.efi`, the other archs are not built via the Dockerfile

Argh, docker - it DTRT if you run on an i386 host. I'll see if I can tweak it to build i386 on amd64 too.

**Comment by ecos-platypus** [comment]
> Argh, docker - it DTRT if you run on an i386 host. I'll see if I can tweak it to build i386 on amd64 too.

I am not sure about Docker but Podman has the flag `--arch` for setting the architecture of the image that is built. I was able to reproduce the i386 build with podman using `--arch i386`. Extending the Dockerfile so that you can reproduce shim for both architectures with one command is nice but I guess two builds are totally fine as long as you know that this is the way to go.

**Comment by steve-mcintyre** [comment]
ACK. I don't see an easy way to do that in docker. Time to switch to podman all round, I think!

**Comment by frozencemetery** [comment]
Looks good to me!

**Comment by steve-mcintyre** [comment]
Closing, signing never happened
