### ISSUE TITLE
Shim 15.7 (NX Patched) for ZeronsoftN

### ISSUE THREAD

**Issue by joseph-zeronsoftn** [rhboot/shim-review#324]
Confirm the following are included in your repo, checking each box:

 - [X] completed README.md file with the necessary information
 - [X] shim.efi to be signed
 - [X] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [X] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [X] any extra patches to shim via your own git tree or as files
 - [X] any extra patches to grub via your own git tree or as files
 - [X] build logs
 - [X] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/zeronsoftn/shim-review/tree/zeronsoftn-shim-x86_64-20230310

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************

```
0cce8d1b89075739840a30db40ff9cb0a372b0b38c0e50afd4225379de61ef35  shimaa64.efi
6fa59470093eae65bee01d88e576e83ba92e7bff9222f391f349c41245e59b8c  shimia32.efi
c9c614bd36ba5399b68dae79f023ba3d9e3af590778fa080961cd10c671fd328  shimx64.efi
```

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
#147 (Accepted)
#254 (15.6, Closed)

**Comment by jclab-joseph** [comment]
> By linking to the alpine-packages repository I thought there were these upstream commits presented somewhere. Or a snapshot of your kernel. I don't understand, why is the link in here then. Isn't this a bit confusing?
We have separated the repository separately to distinguish the kernel we use.

It said that it was applied because the 5.15 kernel already included the three patches mentioned in shim-review.
**NX support patch has not been applied.** This is clearly the part I'm missing. Only the patches mentioned in shim-review have been applied.

> After downloading the archive at http://deb.debian.org/debian/pool/main/g/grub2/grub2_2.06-3~deb11u5.debian.tar.xz I inspected the modules listed in the build-efi-images file.
There seems to be a huge difference between the modules listed in this review and in that file. See for yourself:
(the ones with < are mentioned only in your review, the ones with > are mentioned only in build-efi-images)

Rather than using build-efi-images, we create a new grub image containing the modules we need via grub-mkstandalone. For this part I said `We also generate a single executable grub.efi with the grub-mkstandalone tool with check_signatures enabled to prevent tampering with grub's configuration.`

> Why does your SBAT entry mention the empty repository https://github.com/zeronsoftn/shim-release?
Asking just out of curiosity since the same entry was accepted in an earlier review.

The link in the SBAT entry is a separate repository for issue management so that we can explain about it when there is a problem with the shim we have deployed. It's empty as it hasn't been deployed to production yet, but later we'll write down which images we've signed.


Thank you for your review.

**Comment by joseph-zeronsoftn** [comment]
> By linking to the alpine-packages repository I thought there were these upstream commits presented somewhere. Or a snapshot of your kernel. I don't understand, why is the link in here then. Isn't this a bit confusing?

We have separated the repository separately to distinguish the kernel we use.
It said that it was applied because the 5.15 kernel already included the three patches mentioned in shim-review.
**NX support patch has not been applied.** This is clearly the part I'm missing. Only the patches mentioned in shim-review have been applied.

> After downloading the archive at http://deb.debian.org/debian/pool/main/g/grub2/grub2_2.06-3~deb11u5.debian.tar.xz I inspected the modules listed in the build-efi-images file.
There seems to be a huge difference between the modules listed in this review and in that file. See for yourself:
(the ones with < are mentioned only in your review, the ones with > are mentioned only in build-efi-images)

Rather than using build-efi-images, we create a new grub image containing the modules we need via grub-mkstandalone. For this part I said `We also generate a single executable grub.efi with the grub-mkstandalone tool with check_signatures enabled to prevent tampering with grub's configuration.`

> Why does your SBAT entry mention the empty repository https://github.com/zeronsoftn/shim-release?
Asking just out of curiosity since the same entry was accepted in an earlier review.

The link in the SBAT entry is a separate repository for issue management so that we can explain about it when there is a problem with the shim we have deployed. It's empty as it hasn't been deployed to production yet, but later we'll write down which images we've signed.


Thank you for your review.
