### ISSUE TITLE
Service Planet Rotterdam B.V.-shim-x86_64-20181026

### ISSUE THREAD

**Issue by waikontse** [rhboot/shim-review#38]
This repo is for review of requests for signing shim.  To create a request for review:

- [x] clone this repo
- [x] edit the template below
- [x] add the shim.efi to be signed
- [x] add build logs
- [x] commit all of that
- [x] tag it with a tag of the form "myorg-shim-arch-YYYYMMDD"
- [x] push that to github
- [x] file an issue at https://github.com/rhboot/shim-review/issues with a link to your tag

Note that we really only have experience with using grub2 on Linux, so asking
us to endorse anything else for signing is going to require some convincing on
your part.

Here's the template:

-------------------------------------------------------------------------------
What organization or people are asking to have this signed:
-------------------------------------------------------------------------------
`Service Planet Rotterdam B.V.`

-------------------------------------------------------------------------------
What product or service is this for:
-------------------------------------------------------------------------------

``` no-highlight
The product for which we are applying for shim signing is an appliance codenamed
"Cyric" which is designed to help support personnel in stores. Cyric consists of
a server and a client. The Cyric client is a Linux distribution which users can
boot via PXE or USB on any PC. Once the Linux distribution is booted the user is
launched into a special application and presented with a menu of diagnostic and
options interesting for store customer support personnel.
```

-------------------------------------------------------------------------------
What's the justification that this really does need to be signed for the whole world to be able to boot it:
-------------------------------------------------------------------------------

``` no-highlight
Cyric deals with a very large amount of different models, brands and types of
consumer PC's that are not under our direct control or ownership. Unfortunately
because we deal with a vast number of different types of consumer notebooks and
desktops we encounter all kinds of problems with UEFI's. Some of them don't have
the ability to turn of secure boot even though that ability was mandated for
getting the Windows sticker on the PC at that time. Some UEFI's are so
complicated or poorly designed that even support personel (which operate Cyric)
have trouble finding the off switch. Some machines interpret disabling secure
boot as "enable BIOS compatibility" and can no longer boot via UEFI. Also
Microsoft has dropped the requirement for UEFI implementations that they have to
provide the ability to disable secure boot. So besides that we would like to
offer our users a more seamless experience (not having to manually disable
secure boot and then not forgetting to re-enable it) we encounter a lot of
situations in which we need a signed bootloader. We also anticipate that the
need for being "supported by default" (ie. a signed shim) will only grow now
that Microsoft has dropped the requirement to disable secure boot.
```

-------------------------------------------------------------------------------
Who is the primary contact for security updates, etc.
-------------------------------------------------------------------------------
- Name: Jasper Siepkes
- Position: ICT Manager (Co-founder), Developer
- Email address: siepkes@serviceplanet.nl
- PGP key, signed by the other security contacts, and preferably also with signatures that are reasonably well known in the linux community:
PGP Key ID: 0x9EF4EC108BEF11C5
PGP Key Fingerprint: A15F E099 A0D2 5523 7CF5  5E16 9EF4 EC10 8BEF 11C5

-------------------------------------------------------------------------------
Who is the secondary contact for security updates, etc.
-------------------------------------------------------------------------------
- Name: Wai Kon Tse
- Position: Developer
- Email address: tse@serviceplanet.nl
- PGP key, signed by the other security contacts, and preferably also with signatures that are reasonably well known in the linux community:
PGP Key ID: 0xD20A5F35772B17D4
PGP Key Fingerprint: 4932 5B19 1DB2 26F9 3F0E 56B6 D20A 5F35 772B 17D4

-------------------------------------------------------------------------------
What upstream shim tag is this starting from:
-------------------------------------------------------------------------------
`https://github.com/rhboot/shim/releases/tag/12`

-------------------------------------------------------------------------------
URL for a repo that contains the exact code which was built to get this binary:
-------------------------------------------------------------------------------
https://github.com/serviceplanet/shim-builder

-------------------------------------------------------------------------------
What patches are being applied and why:
-------------------------------------------------------------------------------
`There are no patches being applied.`

-------------------------------------------------------------------------------
What OS and toolchain must we use to reproduce this build?  Include where to find it, etc.  We're going to try to reproduce your build as close as possible to verify that it's really a build of the source tree you tell us it is, so these need to be fairly thorough. At the very least include the specific versions of gcc, binutils, and gnu-efi which were used, and where to find those binaries.
-------------------------------------------------------------------------------

``` no-highlight
We are using CentOS 7.5 and the bundled gcc. Everything can be reproduced by
following the guide provided by the url **https://github.com/serviceplanet/shim-builder**
```

-------------------------------------------------------------------------------
Which files in this repo are the logs for your build?   This should include logs for creating the buildroots, applying patches, doing the build, creating the archives, etc.
-------------------------------------------------------------------------------
build_log

-------------------------------------------------------------------------------
Put info about what bootloader you're using, including which patches it includes to enforce Secure Boot here:
-------------------------------------------------------------------------------

``` no-highlight
We are using grub2 bootleader provided by CentOS 7.5.1804. Grub2 provided by
CentOS 7.5.1804 contains secure-boot patches.
The srpm of CentOS 7.5.1804 grub2 is located at http://vault.centos.org/7.5.1804/os/Source/SPackages/grub2-2.02-0.65.el7.centos.2.src.rpm
```

-------------------------------------------------------------------------------
Put info about what kernel you're using, including which patches it includes to enforce Secure Boot here:
-------------------------------------------------------------------------------

``` no-highlight
The kernel we are using is fedora 28 kernel tagged **kernel-4.16.14-300.fc28**
with commit hash of **217860d07996562757ba22a1108c218c5a40b38e**.
```

--------------------------------------------------------------------------------
Location of certificate
--------------------------------------------------------------------------------
https://github.com/serviceplanet/shim-builder/blob/master/keys/sp_code_signing_cert.der

--------------------------------------------------------------------------------
sha256 of shimx64.efi
--------------------------------------------------------------------------------

``` no-highlight
b52df1bd99a29cd4e6f53c799fc6c2c89650925c8f073c8fdd1b21fcf985bd02  shimx64.efi
```

--------------------------------------------------------------------------------
Microsoft Uefi submission ID
--------------------------------------------------------------------------------

``` no-highlight
14105650530628646
```

--------------------------------------------------------------------------------
Location of build log and produced binary
--------------------------------------------------------------------------------
https://github.com/serviceplanet/shim-review

**Comment by waikontse** [comment]
Hi @cyphermox,

I wanted to ask if you've any time to review the shim that is posted for review or you've encountered any difficulties trying to reproduce the steps described in the readme at https://github.com/serviceplanet/shim-builder. This is our second submission for a review, because the EV code certificate of our previous approved shim is almost expired.

Thanks,
Wai kon Tse

**Comment by cyphermox** [comment]
Build is reproducible with the minimal differences expected on a shim 12 build. Please consider upgrading to a newer version of shim.

I find this shim acceptable for signing:

`[root@sound-loon shim-review]# sha256sum shimx64.efi 
b52df1bd99a29cd4e6f53c799fc6c2c89650925c8f073c8fdd1b21fcf985bd02  shimx64.efi`

Differences found were consistent with expectations for shim 12:
 - one byte diff here and there in PE, COFF headers.
 - different data.ident due to build environment (I reproduced in LXD container for centos/7)
 - different ephemeral key for signing fb/mm
 - one byte difference in dynsym.

`@@ -11,7 +11,7 @@
 000000a0  00 7e 07 00 00 00 00 00  00 40 02 00 00 40 02 00  |.~.......@...@..|
 000000b0  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
 000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
-000000d0  00 e0 11 00 00 04 00 00  3c 8f 14 00 0a 00 00 00  |........<.......|
+000000d0  00 e0 11 00 00 04 00 00  aa 62 14 00 0a 00 00 00  |.........b......|
 000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000100  00 00 00 00 10 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -30,7 +30,7 @@
 000001d0  00 00 00 00 20 00 50 60  2e 72 65 6c 6f 63 00 00  |.... .P`.reloc..|
 000001e0  0a 00 00 00 00 f0 0b 00  00 02 00 00 00 92 0b 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 40 00 10 42  |............@..B|
-00000200  2f 31 34 00 00 00 00 00  d4 00 00 00 00 10 0c 00  |/14.............|
+00000200  2f 31 34 00 00 00 00 00  cd 00 00 00 00 10 0c 00  |/14.............|
 00000210  00 02 00 00 00 94 0b 00  00 00 00 00 00 00 00 00  |................|
 00000220  00 00 00 00 40 00 60 c0  2e 64 61 74 61 00 00 00  |....@.`..data...|
 00000230  58 be 02 00 00 20 0c 00  00 c0 02 00 00 96 0b 00  |X.... ..........|
@@ -8524,7 +8524,7 @@
 000214b0  e9 cc 00 00 00 48 83 7d  f8 00 0f 84 af 00 00 00  |.....H.}........|
 000214c0  48 8b 45 f8 8b 00 89 c0  48 8d 50 f8 48 8b 45 f8  |H.E.....H.P.H.E.|
 000214d0  48 8d 48 08 48 c7 44 24  28 20 00 00 00 48 8d 45  |H.H.H.D$( ...H.E|
-000214e0  a4 48 89 44 24 20 41 b9  a7 03 00 00 4c 8d 05 4d  |.H.D$ A.....L..M|
+000214e0  a4 48 89 44 24 20 41 b9  a8 03 00 00 4c 8d 05 4d  |.H.D$ A.....L..M|
 000214f0  14 0b 00 e8 56 51 00 00  84 c0 74 0e 48 c7 45 c8  |....VQ....t.H.E.|
 00021500  00 00 00 00 48 8b 45 c8  eb 77 48 8d 05 c7 76 0c  |....H.E..wH...v.|
 00021510  00 8b 00 85 c0 74 58 48  8d 05 ba 76 0c 00 8b 00  |.....tXH...v....|
`
`@@ -66334,7 +66334,7 @@
 001031d0  07 61 07 00 00 00 00 00  2c 00 00 00 00 00 00 00  |.a......,.......|
 001031e0  83 1f 00 00 11 00 07 00  e0 35 0e 00 00 00 00 00  |.........5......|
 001031f0  38 00 00 00 00 00 00 00  f8 03 00 00 11 00 06 00  |8...............|
-00103200  00 10 0c 00 00 00 00 00  d4 00 00 00 00 00 00 00  |................|
+00103200  00 10 0c 00 00 00 00 00  cd 00 00 00 00 00 00 00  |................|
 00103210  53 bc 00 00 11 00 07 00  70 c1 0e 00 00 00 00 00  |S.......p.......|
 00103220  10 00 00 00 00 00 00 00  51 1a 00 00 12 00 03 00  |........Q.......|
 00103230  ca 8b 03 00 00 00 00 00  42 01 00 00 00 00 00 00  |........B.......|`

**Comment by waikontse** [comment]
@cyphermox Thank you for your time and for reviewing our shim.  As we are currently using centOS 7.5, we are currently stuck with shim12. When we update, we'll be sure to update to shim15 as well.
