### ISSUE TITLE
Shim 15.8 for ALT Linux (altlinux-shim-ia32-x64-20240315)

### ISSUE THREAD

**Issue by Blarse** [rhboot/shim-review#384]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/Blarse/shim-review/tree/altlinux-shim-ia32-x64-20240315

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
```
dc20046109d30c8353a6cf37e6666901d9bdfe38b9ac7166652ca9c3a064e742  ./shimia32.efi
7b698a7100eabf0e75f5896e898156e4d122b06f04467365ca79c3295d48b8b3  ./shimx64.efi
```

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
N/A

**Comment by SherifNagy** [comment]
Just a quick note, is Alt Linux an actual organisation? usually as per my understanding, you need to provide whatever organisation that singing this SHIM , that usually will have the EV cert issued for which will be added to Microsoft partner program, I couldn't find anything online about an official organisation called Alt Linux.

Another question is regarding the SHIM patch, I understand you are dropping shim.debian since you aren't debian based, but have you considered instead of patching SHIM, just adding the grub2 hashes you don't want to load into dbx file in SHIM?

**Comment by Blarse** [comment]
Hi @SherifNagy,

> Just a quick note, is Alt Linux an actual organisation? usually as per my understanding, you need to provide whatever organisation that singing this SHIM , that usually will have the EV cert issued for which will be added to Microsoft partner program, I couldn't find anything online about an official organisation called Alt Linux.

No worries, ALT Linux Team is represented by ALT Linux LLC, this organization actually exists and we have EV certificate.

> Another question is regarding the SHIM patch, I understand you are dropping shim.debian since you aren't debian based, but have you considered instead of patching SHIM, just adding the grub2 hashes you don't want to load into dbx file in SHIM?

Well, besides we aren’t Debian-based distro, I don’t see any reason not to set grub revocation to 4 as it already required for the grub binary to have SBAT level 4 after fixing NTFS vulnerabilities. We don't have any signed grub binaries vulnerable to this issue, so no need for dbx file. If there really is a reason not to do so, I would be happy to discuss it here.

**Comment by steve-mcintyre** [comment]
Added the "new vendor" label - new people involved

**Comment by SherifNagy** [comment]
@Blarse Thanks for the clarification, I am just thinking out loud here with you
* If you don't have any signed grub binaries with NTFS vulnerability, then the only grub will boot is the singed "NTFS patched" grub even if SBAT revocation list is allowing grub,3 with NTFS vulnerability to boot, it won't boot in secure boot enabled environment since it is not signed
* The patch itself is fine and do what it says on the tin :) and I think it is okay to keep the patch if this is what you want, also it is okay to remove the patch since you never signed any vulnerable grub before "since it looks like you are using a new CA", I assume next shim release will revoke grub,3 anyway once distors backport the NTFS CVE fixes "even if they don't ship NTFS module"

I will be continue reviewing the issue with the patch in place

**Comment by SherifNagy** [comment]
While I am not an official reviewer, here are my comments "looking at latest tag: https://github.com/Blarse/shim-review/tree/altlinux-shim-ia32-x64-20240219":

* SHIM's CA valid for almost 13 years and it's 4096 bits and it's a new CA
* SHIM binary reproducible correctly and hashes matches
* SHIM SBAT entries looks good for shim 15.8 "shim,4"
* SHIM SBAT entry for the vendor remains at 1 which is good
* SHIM patch to revoke grub < 4 looks good since they provide NTFS module
* Kernel lockdown patches present
* Ephemeral keys used to sign kernel modules
* CA and certs protection with HSM story looks good

The are few grub patches for EFI, revoke commit 80ec3cf5dc396aaeb18dbc582c4ac5331439e349 and other , would need another set of eyes from trusted reviewers to look at those

Notes:
* New legal entity
* Can't find any contact verification and seems to be also they are new security contacts
* We will need two more trusted reviewers

**Comment by SherifNagy** [comment]
I couldn't find a contact verification trail, so I am sending an email in few minutes

**Comment by Blarse** [comment]
@SherifNagy Thank you very much for the review.

> The are few grub patches for EFI, revoke commit 80ec3cf5dc396aaeb18dbc582c4ac5331439e349 and other , would need another set of eyes from trusted reviewers to look at those

The commit 80ec3cf5dc396aaeb18dbc582c4ac5331439e349 is cherry-picked 93a786a00 (kern/efi/sb: Enforce verification of font files) which breaks the ability to load ALT Linux based distributions grub themes with arbitrary font files.

If this revocation is considered as an insecure solution, then according to this discussion[1] there is no way to sign individual font files and the only way to load verified fonts is to bundle them as memdisk into grub efi image. Should we act this way?

[1] https://lists.gnu.org/archive/html/grub-devel/2022-12/msg00070.html

**Comment by Blarse** [comment]
> I couldn't find a contact verification trail, so I am sending an email in few minutes

soo5Bah7 phae8ieR iem3eiXo Boji6chu Oa9ootho co6ahL4v

**Comment by SherifNagy** [comment]
> @SherifNagy Thank you very much for the review.
> 
> > The are few grub patches for EFI, revoke commit 80ec3cf5dc396aaeb18dbc582c4ac5331439e349 and other , would need another set of eyes from trusted reviewers to look at those
> 
> The commit 80ec3cf5dc396aaeb18dbc582c4ac5331439e349 is cherry-picked 93a786a00 (kern/efi/sb: Enforce verification of font files) which breaks the ability to load ALT Linux based distributions grub themes with arbitrary font files.
> 
> If this revocation is considered as an insecure solution, then according to this discussion[1] there is no way to sign individual font files and the only way to load verified fonts is to bundle them as memdisk into grub efi image. Should we act this way?
> 
> [1] https://lists.gnu.org/archive/html/grub-devel/2022-12/msg00070.html

I think disabling this will expose end users to attacks, I am tagging @THS-on and @steve-mcintyre for more info regarding this and maybe a work around

**Comment by steve-mcintyre** [comment]
@Blarse yes, the recommended way now it build the fonts into the memdisk so they come from a signed (and therefore trusted) source. Disabling a security-related change in grub here is *not* an option for Secure Boot.

**Comment by Blarse** [comment]
> @Blarse yes, the recommended way now it build the fonts into the memdisk so they come from a signed (and therefore trusted) source. Disabling a security-related change in grub here is *not* an option for Secure Boot.

Alright, than I will rebuild our grub with fonts embedded into memdisk and update the submission in a few days.

**Comment by glebfm** [comment]
> I couldn't find a contact verification trail, so I am sending an email in few minutes

jeo6EYov Naipei3c chaiYeW4 sithuG3h eecoZee2 quaeGuY7

**Comment by SherifNagy** [comment]
Contacts has been verified

**Comment by Blarse** [comment]
> > @Blarse yes, the recommended way now it build the fonts into the memdisk so they come from a signed (and therefore trusted) source. Disabling a security-related change in grub here is _not_ an option for Secure Boot.
> 
> Alright, than I will rebuild our grub with fonts embedded into memdisk and update the submission in a few days.

I have rebuilt grub with recommended patch and fonts embedded into memdisk.
The updated submission is available at https://github.com/Blarse/shim-review/tree/altlinux-shim-ia32-x64-20240315

There are 3 new grub patches for enabling font verification enforcement:
0098-kern-efi-sb-Enforce-verification-of-font-files.patch -- reapplied font verification enforcement
0099-font-Try-opening-fonts-from-the-bundled-memdisk.patch -- patch to load fonts from memdisk
0100-kern-file-Fix-error-handling-in-grub_file_open.patch -- fix needed for loading font files

**Comment by jsetje** [comment]
I suppose I should have created a build time configurable latest sbat payload, that said, the patch is obvious enough. I'll look into creating the right infrastructure so this doesn't have to become a regular thing.

I see no reason to tell anyone they can't be more secure. Finally this is the opt-in latest revocation, so someone that breaks a multi-boot scenario did that to themselves and can presumably disable secure boot to roll back.

**Comment by Blarse** [comment]
Thank you all for the review.

Microsoft submission IDs:
shimx64.efi 14348405321342813
shimia32.efi 14575264375118117
