### ISSUE TITLE
Debian GNU/Linux 13 (trixie) shim-15.8-1 x64 and aarch64

### ISSUE THREAD

**Issue by steve-mcintyre** [rhboot/shim-review#415]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
`https://github.com/steve-mcintyre/shim-review/tree/debian-13-shim-amd64-arm64-20240512`

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
```
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  shimaa64.efi
81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  shimx64.efi
```

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/315

*******************************************************************************
### If no security contacts have changed since verification, what is the link to your request, where they've been verified (if any, otherwise N/A)?
*******************************************************************************
Pass - we've been submitting shims for years!

**Comment by THS-on** [comment]
# Review of `debian-13-shim-amd64-arm64-20240512`

* Debian is a well known Linux distro
* This is the shim for Debian 13
* Security contacts haven't changed

## Shim
*. Based on 15.8
  * Includes patch to revoke `grub.peimage` < 2 (https://salsa.debian.org/efi-team/shim/-/blob/master/debian/patches/0001-sbat-Add-grub.peimage-2-to-latest-CVE-2024-2312.patch?ref_type=heads)
  * Includes patch to revoke `grub`< 4 (https://salsa.debian.org/efi-team/shim/-/blob/master/debian/patches/0002-sbat-Also-bump-latest-for-grub-4-and-to-todays-date.patch?ref_type=heads)
  * CA has not changed (valid till 2046)
   * Leaf certificates changed
* Build is reproducible
```
81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim/shimx64.efi
81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim-review/shimx64.efi

75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim/shimaa64.efi
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim-review/shimaa64.efi
``` 
* NX is disabled

## GRUB
* Based on 2.12 + decent amount of patches
* Includes NTFS module
  * SBAT is set to 4 and includes patches (are in upstream)
* Module list looks fine
  *  Biggest change including peimage (with additional SBAT entry) and removing linuxefi (More details: https://salsa.debian.org/grub-team/grub/-/commits/master/debian/build-efi-images?ref_type=heads)
* SBAT looks fine
  * Adds `grub.debian13` and `grub.peimage` entries

## fwupd and systemd-boot
* SBAT looks fine
* systemd-boot or UKIs are currently not signed

## Kernel
* Includes the usual lockdown patches and fixes
* Debian latest development switched to ephemeral key signing, certificates are switched once all builds do this.
 
## Questions and Notes
* There is a separate `grub.debian13` entry for easier revocation per version. A reason not to do this also for shim etc.?
* The new leaf certificates are the 2022 ones (https://salsa.debian.org/ftp-team/code-signing/-/tree/master/etc?ref_type=heads), right?
* The backports kernels also now use ephemeral key signing. If I see it correctly the older stable kernels are the only ones missing.
* What is the state of the peimage patch set going upstream?

**Comment by steve-mcintyre** [comment]
> ## Questions and Notes
> 
>     * There is a separate `grub.debian13` entry for easier revocation per version. A reason not to do this also for shim etc.?

Good question, with an easy answer! We just haven't got there yet. I'll add it to the list of things to do for the next upload, if that's OK?

>     * The new leaf certificates are the 2022 ones (https://salsa.debian.org/ftp-team/code-signing/-/tree/master/etc?ref_type=heads), right?

Correct - we're currently using the 2022 certs. We've started the process to generate new 2024 signer certs, and that's where we'll be looking to change config slightly:
- add a signer ready for use with systemd-boot when we're ready
- use the new kernel signer **only** with builds that use ephemeral keys.

>     * The backports kernels also now use ephemeral key signing. If I see it correctly the older stable kernels are the only ones missing.

Stable and oldstable and oldoldstable... :-)

>     * What is the state of the peimage patch set going upstream?

Kukri is working on upstreaming it, and we hope to have it accepted in the next grub upstream release.

**Comment by THS-on** [comment]
> > * There is a separate `grub.debian13` entry for easier revocation per version. A reason not to do this also for shim etc.?
> 
> Good question, with an easy answer! We just haven't got there yet. I'll add it to the list of things to do for the next upload, if that's OK?

Yeah, as long as for example the Shim uses the same version, CA and patches, there is not much to differentiate. Once those diverge between version a per version SBAT makes more sense (as its the case for GRUB2).
 
> > * The new leaf certificates are the 2022 ones (https://salsa.debian.org/ftp-team/code-signing/-/tree/master/etc?ref_type=heads), right?
> 
> Correct - we're currently using the 2022 certs. We've started the process to generate new 2024 signer certs, and that's where we'll be looking to change config slightly:
> 
>     * add a signer ready for use with systemd-boot when we're ready
> 
>     * use the new kernel signer **only** with builds that use ephemeral keys.
> 

Sounds good!
 
> > * What is the state of the peimage patch set going upstream?
>
> Kukri is working on upstreaming it, and we hope to have it accepted in the next grub upstream release.

Great! From my side this LGTM! Let's get one more review before accepting.

**Comment by akodanev** [comment]
I will try to contribute to the review, but I am not an official reviewer.

Shim review of debian-13-shim-amd64-arm64-20240512
----

1. Embedded root certificate valid until 2046 - no changes.

2. There are two additional upstream patches applied to the shim-15.8 release:

- commit 3e1394e ("sbat: Also bump latest for grub,4 (and to todays date)")
- commit 63edf92 ("sbat: Add grub.peimage,2 to latest (CVE-2024-2312)")

shim aarch64/x86_64 `.sbat` and `.sbatlevel` sections have the following entries:

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.debian,1,Debian,shim,15.8,https://tracker.debian.org/pkg/shim

sbat,1,2024010900
shim,4
grub,3
grub.debian,4
sbat,1,2024040900
shim,4
grub,4
grub.peimage,2
```

All is expected according to the applied extra patches and pre-set `SBAT_AUTOMATIC_DATE`.
Latest policy for grub: `grub,4` (since builds include NTFS module) and `grub.peimage,2`
entry to revoke grub builds affected by CVE-2024-2312.

3. For both binaries, the NX bit is not set.

4. shim builds are reproducible:

* `x86_64`: 

```
#24 [21/23] RUN sha256sum /shim/shim*.efi /shim-review/$(basename /shim/shim*.efi)
#24 0.336 81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim/shimx64.efi
#24 0.339 81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim-review/shimx64.efi
#24 DONE 0.4s
```

* `aarch64` build as well:

```
Step 23/23 : RUN sha256sum /shim/shim*.efi /shim-review/$(basename /shim/shim*.efi)
 ---> Running in a9833b52000c
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim/shimaa64.efi
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim-review/shimaa64.efi
```

fwupd, systemd-boot
-------------------
SBAT entries look good.


GRUB
----
GRUB is based on the upstream grub-2.12 release with the required CVE fixes.
Corresponding grub `.sbat` section contains `grub,4` and `grub.peimage,2`.


Linux kernel
------------

The Linux kernel has the lockdown patches: https://salsa.debian.org/kernel-team/linux/-/tree/sid/debian/patches/features/all/lockdown, and uses a build-time generated key for module signing.

LGTM!

**Comment by SherifNagy** [comment]
# Review of [debian-13-shim-amd64-arm64-20240512](https://github.com/steve-mcintyre/shim-review/tree/debian-13-shim-amd64-arm64-20240512)
* Debian is very well known big time distro
* Security contacts looks good, didn't change
* Keys are stored in HSM and  kernel using in-built ephemeral keys

## Shim
* Uses upstream 15.8 and source hashes matches original hashes
* SBAT entries from shim looks fine `shim,4`
* Vendor SBAT entry is at 1
* patches looks fine and cherry picked from upstream 
* Binaries are reproducible using the container file provided
```
STEP 23/23: RUN sha256sum /shim/shim*.efi /shim-review/$(basename /shim/shim*.efi)
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim/shimaa64.efi
75715344ceaf0faedc7574ea9d41c82d54c657772b9b7e700c43700f8730f450  /shim-review/shimaa64.efi
```
```
STEP 23/23: RUN sha256sum /shim/shim*.efi /shim-review/$(basename /shim/shim*.efi)
81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim/shimx64.efi
81b5ea382dbf336107076b209521217487b9031237e8741577e5ddf2ef11a412  /shim-review/shimx64.efi
```
* NX flag is not set, because the chain is not yet ready
* Self signed 2048 bit cert and valid for 22 years

## GRUB2
* SBAT looks fine, however, I thought that Debian will keep it at `grub.debian,4`, I know there is no harm of going to `grub.debian,5` but what's the reason behind this bump?
* NTFS patches are in place
* Module list sound fine

## Kernel
* Ephemeral keys are used for signing kernel modules
* Lockdown patches are included
* UKI's isn't provided

LGTM, other than this grub question SBAT entry question

**Comment by steve-mcintyre** [comment]
> I will try to contribute to the review, but I am not an official revi

Thanks!

**Comment by steve-mcintyre** [comment]
> * SBAT looks fine, however, I thought that Debian will keep it at `grub.debian,4`, I know there is no harm of going to `grub.debian,5` but what's the reason behind this bump?

We're thinking about potential future issues with grub filesystems, basically. Over time we're looking at removing some of less common filesystems for newer Debian releases, and this gives us some differentiation against the grub builds in older releases. It's not doing much *yet*, admittedly.

**Comment by SherifNagy** [comment]
All looks good to me then, @THS-on I think we can accept

**Comment by steve-mcintyre** [comment]
We have signed shims now, closing.
