### ISSUE TITLE
ECOS_Technology_GmbH-shim-x64-20190531

### ISSUE THREAD

**Issue by richterger** [rhboot/shim-review#70]
- [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag

https://github.com/richterger/shim-review @ECOS_Technology_GmbH-shim-x64-20190531

 - [x] completed README.md file with the necessary information

https://github.com/richterger/shim-review/blob/master/README.md

 - [x] shim.efi to be signed

https://github.com/richterger/shim-review/blob/master/shimx64.efi       

 - [x ] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)

https://github.com/richterger/shim-review/blob/master/patches-shim/ECOS_Tech_Code_signing_Certificate_EV.cer

 - [x] any extra patches to shim via your own git tree or as files

https://github.com/richterger/shim-review/tree/master/patches-shim

 - [x] any extra patches to grub via your own git tree or as files

https://github.com/richterger/shim-review/tree/master/patches-grub

 - [x] build logs

https://github.com/richterger/shim-review/blob/master/shim_build.log

###### What organization or people are asking to have this signed:

ECOS Technology GmbH

https://www.ecos.de/

###### What product or service is this for:

ECOS SECURE BOOT STICK (SBS)

https://www.ecos.de/produkte/zugangskomponenten/secure-boot-stick/

This is a secure ThinClient on a USB Stick, the SBS [SX] Version is approved
by the german BSI to use in govermental organisation

###### What is the origin and full version number of your shim?

https://github.com/rhboot/shim.git
commit a4a1fbe728c9545fc5647129df0cf1593b953bec 15 Mar 2019

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:

The SBS need to work in every computer, so it's necessary to have a public
signed bootloader.
Since we build the kernel and all our binaries on our own, we need to be
able to sign them with our signature, hence we need a public signed
bootloader.

###### How do you manage and protect the keys used in your SHIM?

The key is stored on a FIPS-140-2 Token. The key is part of our EV code
signing certificate.

###### Do you use EV certificates as embedded certificates in the SHIM?

yes

###### What is the origin and full version number of your bootloader (GRUB or other)?

https://www.gnu.org/software/grub/

Gentoo ebuild grub-2.02-r3

###### If your SHIM launches any other components, please provide further details on what is launched

shim is patched to only be able to launch our own grub. Launching any other
code (like Mok-Manager, Fallback etc.) has been removed from shim

###### How do the launched components prevent execution of unauthenticated code?

Our grub has the following patches:

- Grub is build and shipped as one static binary. No modules are used.
- The code to load a module at runtime (insmod) has been removed from our grub
- Grub is signed with our EV code signing certificate
- Grub only loads a kernel that was signed by us. There is no way to load any code that is not correctly signed with our certificate.
- Also other files like background images are only loaded if they are correctly signed
- There is no way to add a user certificate.
- The Linux Kernel we use, uses signed modules and only loads modules that are correctly signed with our certificate.
- grub.cfg is embbeded in the signed grub binary

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

Kernel 4.14, 4.19 and 5.1. Our kernel and all modules are signed
by our key and kernel enforces that only correctly signed modules are
loaded.

###### What changes were made since your SHIM was last signed?

Updated from shim 0.9 to 0.15+

###### What is the hash of your final SHIM binary?

8f6b33b2fb10f6333ef37f0b8aac70b8ab73b121588879f3c6d28eed550f8f53  shimx64.efi

**Comment by richterger** [comment]
Hi, it would be great if it is possible to start the verification process for our shim, since the certificate that is build in our old shim we are using right now will expires soon and then we are not able to provide any (security) updates to our customers any more. If there is anything I can do to help to speed things up, let me know. Thanks!

**Comment by stolzchr** [comment]
Hi all - is there already kind of a schedule for our request? Anything we can do or provide in addition that helps progressing the request? Any hint would be highly appreciated.
Many thanks in advance.

**Comment by cyphermox** [comment]
Rebuild test not completed yet; but at a glance this has all the earmarks of a third-party bootloader. Grub has been modified extensively with various patches, include rewriting things that already exists (signature verification for files), and shim has also been largely modified to disable some features. I'm not comfortable approving this directly as a proper "shim", so I'll defer to Microsoft's judgement when dealing with custom second-stage bootloaders.

I have still to do the rebuild test, to make sure this is at least a reproducible build, then I'll add the appropriate tag to this issue.

By the way, you can achieve much of what you want without changing code in shim: just do not ship fallback or MokManager. Keys might still be manageable in firmware directly, but that's /difficult/, and not made impossible by your changes anyway.

**Comment by stolzchr** [comment]
Well ... many thanks so far.
Just let us know where we can help progressing this issue or contribute to make the "whys" comprehensible.

**Comment by stolzchr** [comment]
Brief addition - we had an internal discussion about your feedback and thought it would be helpful to provide some insights about our motives.

Primary target on our end is supporting the UEFI secure boot in a highly secured way where we are now looking at the third revision within the last six years of our version of shim and grub.
The first two versions where approved and signed by Microsoft.
Thus there is already a more than six year history with additional security features we built on our end because that wasn't available with grub at this time.
With the current request we rebased the implementation on the latest grub version but didn't adapt to all newer grub features where our implementation has proven a high security and robustness.
On the other hand we disabled features in shim code that might pose a point of attack in our application scenarios (e.g MoKManager).

Nevertheless - if there are certain issues that prevent you from approving our request, please let us know. We are absolutely willing to come to a satisfying result on either side.

**Comment by AlexeyPetrenkoOracle** [comment]
It's five months since this review request was submitted without any progress.
This process is clearly dysfunctional and puts all Linux distributions at a serious security risk.

**Comment by cyphermox** [comment]
Rebuild is fine; this produces the same binary; but as previously mentioned, I'm not comfortable approving this right out as it depends on a modified GRUB, and shim itself is heavily modified.

As previously stated, the exact same behavior for shim could have been achieved trivially by simply never providing fallback or MokManager; then you don't need to patch out the code starting them (since they need to be appropriately signed to be started by shim anyway).

I'm leaving the final decision to Microsoft (this is what "custom second-stage" tag means).

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
